### ISSUE TITLE
File->Import Database->Graph Database... menu item not available after installation

### ISSUE THREAD

**Issue by jakob-beetz** [datablend/gephi-blueprints-plugin#1]
After installing the gephi-bluprints-plugins (both nbm's) exactly as described in the wiki, no menu option File->import Database->Graph Database is showing up.

Gephi-version 0.8.1 beta

Any help is very much appreciated

**Comment by TimmyStorms** [comment]
Hi Jakob,

I've updated the downloadable files. Can you please try these ones?

The problem was that the org.gephi.blueprints.plugin wasn't eagerly loaded, thus org-gephi-blueprints-plugin.xml has been changed from

``` xml
<module name="org.gephi.blueprints.plugin">
    <param name="autoload">true</param>
    <param name="eager">false</param>
    <param name="jar">modules/org-gephi-blueprints-plugin.jar</param>
    <param name="reloadable">false</param>
</module>
```

to

``` xml
<module name="org.gephi.blueprints.plugin">
    <param name="autoload">false</param>
    <param name="eager">true</param>
    <param name="jar">modules/org-gephi-blueprints-plugin.jar</param>
    <param name="reloadable">false</param>
</module>
```

Although the plugin is specified as "module type:eager" in my development environment, it isn't exported as one. Maybe this is due to a bug in Netbeans, or due to my limited knowlegde of the Netbeans framework. ;-)

Hope this helps!

Timmy

ps: don't forget to add a configuration file in etc/graph to be able to use this plugin!

**Comment by sgomezvillamor** [comment]
Although I've just downloaded the plugins, I have the same problem.

Also, I get this exception when I click "Import database --> Graph database"

```
java.lang.NoClassDefFoundError: Could not initialize class org.gephi.blueprints.plugin.config.GraphConfigurationReader
    at org.gephi.blueprints.plugin.ui.GraphDbImporterUI.getPanel(GraphDbImporterUI.java:29)
    at org.gephi.desktop.importer.DesktopImportControllerUI.importDatabase(DesktopImportControllerUI.java:332)
    at org.gephi.desktop.importer.DesktopImportControllerUI.importDatabase(DesktopImportControllerUI.java:318)
    at org.gephi.desktop.importer.ImportDB$1.actionPerformed(ImportDB.java:92)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2028)
```

Just to provide as much information as possible:
- I'm using Gephi 0.8.1 for Mac OS X
- I've added the xml configuration files here /Users/sgomez/Desktop/gephi.app/Contents/Resources/gephi/etc, but even if there is no configuration file there, I get the exception

**Comment by ntroutman** [comment]
I'm also on a Mac and had to add it into `/etc/graph` which is annoying since it requires root permissions to make a directory their. I would have expected to be able to use `~/Library/Application\ Support/gephi/0.8.2/etc/graph/`.

**Comment by ssadams11** [comment]
The problem is that the module looking for the graph folder is looking in /etc/graph, not ...gephi/etc/graph.
I stuck the graph folder in /etc and it works fine

**Comment by lukosan** [comment]
I'm running gephi on OSX 10.11.16 El Capitan. When I install the plugin I get the "Imports database --> Graph database..." menu item but when I click on it nothing happens.

I notice from the src code that it's looking for the configs in:

`System.getProperty("user.dir") + "/etc/graph/"`

and rumour has it that this sys property isn't particularly reliable on a Mac. I've tried putting the config files in various locations (including /etc/graph and gephi's etc folder which is at /Applications/Gephi.app/Contents/Resources/gephi/etc and even ~/etc/graph) but no change. My struggles are exarcerbated by the fact that I can't for the life of me find where the programme is logging to - does anyone know where the logs are on OSX?
